language: ruby
rvm:
  - 2.2.3
  - 2.3.0
  - 2.3.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
bundler_args: "--jobs=3 --retry=3"
cache: bundler

before_install:
  - gem update bundler
